import { Collection, Slide } from "@/lib/types";

export const slides: Slide[] = [
  {
    id: "slide-001",
    title: "深色述职封面",
    coverImage: "/images/slides/slide-001.jpg",
    category: "cover",
    scenes: ["述职晋升", "工作汇报"],
    tags: ["深色", "高级感", "商务蓝"],
    style: "沉稳商务",
    summary: "适合年度述职与管理层汇报的封面页，以大标题和氛围视觉建立正式感。",
    layoutAnalysis: "左侧大标题配信息栏，右侧保留深色建筑或人物氛围图，底部收纳时间和汇报人信息。",
    visualFocus: "标题与深色背景形成强对比，留白让主标题具备更高权重。",
    reusableTips: "封面页只保留最关键标题、身份和日期，用一张高质背景图建立情绪即可。",
    createdAt: "2026-03-01",
    isFeatured: true,
    popularity: 96,
    topic: "述职汇报",
    dominantTone: "深海蓝",
    sourceType: "editorial",
  },
  {
    id: "slide-002",
    title: "极简品牌提案封面",
    coverImage: "/images/slides/slide-002.jpg",
    category: "cover",
    scenes: ["品牌营销", "商业提案"],
    tags: ["极简", "留白", "黑白灰"],
    style: "极简编辑感",
    summary: "以大留白和精炼标题构成的提案封面，适合品牌与策略类内容。",
    layoutAnalysis: "中心对齐标题搭配细线分割，下方保留提案对象与日期信息。",
    visualFocus: "留白本身就是视觉秩序，文本被精确控制在小范围内。",
    reusableTips: "标题控制在 8 到 12 字内，副标题保持中性色，不要抢主标题。",
    createdAt: "2026-03-02",
    isFeatured: true,
    popularity: 91,
    topic: "营销策划",
    dominantTone: "暖白",
    sourceType: "editorial",
  },
  {
    id: "slide-003",
    title: "路演融资数据封面",
    coverImage: "/images/slides/slide-003.jpg",
    category: "cover",
    scenes: ["路演融资", "产品发布"],
    tags: ["科技感", "深色", "几何"],
    style: "科技简报",
    summary: "用几何线条与高对比数字构成的路演封面，适合科技产品叙事。",
    layoutAnalysis: "上部品牌名与轮次信息，下部标题，背景通过网格和斜线加强未来感。",
    visualFocus: "主标题与右上角关键轮次信息形成双锚点。",
    reusableTips: "融资封面要强调核心身份信息，视觉元素控制在几何与品牌色范围内。",
    createdAt: "2026-03-03",
    isFeatured: true,
    popularity: 84,
    topic: "路演融资",
    dominantTone: "石墨黑",
    sourceType: "editorial",
  },
  {
    id: "slide-004",
    title: "季度复盘目录页",
    coverImage: "/images/slides/slide-004.jpg",
    category: "agenda",
    scenes: ["工作汇报", "述职晋升"],
    tags: ["极简", "商务蓝", "结构清晰"],
    style: "理性商务",
    summary: "适合季度和年度复盘的目录页，突出章节顺序与阅读路径。",
    layoutAnalysis: "顶部标题，下方四栏等宽模块排列，采用数字编号和短句章节名。",
    visualFocus: "连续编号和规整对齐制造稳定节奏。",
    reusableTips: "目录页不要塞满说明，用短标题和统一编号建立秩序即可。",
    createdAt: "2026-03-04",
    isFeatured: true,
    popularity: 93,
    topic: "工作复盘",
    dominantTone: "雾蓝灰",
    sourceType: "editorial",
  },
  {
    id: "slide-005",
    title: "品牌策略目录页",
    coverImage: "editorial-spread",
    category: "agenda",
    scenes: ["品牌营销", "商业提案"],
    tags: ["杂志感", "高对比", "留白"],
    style: "编辑策划",
    summary: "适合品牌策略与整合营销提案，用类似目录编排增强策展感。",
    layoutAnalysis: "左侧大编号，右侧多行章节目录，辅以细线和页码式装饰。",
    visualFocus: "大编号让整页拥有强识别点，目录文本形成次级层次。",
    reusableTips: "当目录内容较多时，优先强化编号系统，文本字重保持统一。",
    createdAt: "2026-03-05",
    isFeatured: false,
    popularity: 82,
    topic: "营销策划",
    dominantTone: "奶油白",
    sourceType: "editorial",
  },
  {
    id: "slide-006",
    title: "产品发布章节过渡",
    coverImage: "launch-stage",
    category: "transition",
    scenes: ["产品发布", "教育培训"],
    tags: ["深色", "大字标题", "科技感"],
    style: "发布会风格",
    summary: "章节切换时使用的强标题过渡页，适合产品发布节奏。",
    layoutAnalysis: "整页只保留章节标题与极少辅助字，背景使用大面积深色渐变。",
    visualFocus: "超大字号与深色背景形成明显停顿感。",
    reusableTips: "过渡页只做一件事，就是让下一段内容被清楚感知，不要加入过多信息。",
    createdAt: "2026-03-06",
    isFeatured: true,
    popularity: 88,
    topic: "产品发布",
    dominantTone: "炭黑",
    sourceType: "editorial",
  },
  {
    id: "slide-007",
    title: "年终总结章节过渡",
    coverImage: "ceremony-red",
    category: "transition",
    scenes: ["工作汇报", "述职晋升"],
    tags: ["红黑", "强标题", "仪式感"],
    style: "总结汇报",
    summary: "用于年终汇报章节切换，强调节点感与正式氛围。",
    layoutAnalysis: "中心标题搭配年份编号和细线，背景使用低透明纹理增加层次。",
    visualFocus: "大标题和年份形成纪念性视觉焦点。",
    reusableTips: "过渡页适合放年份、阶段、主题词，不建议放解释性长文。",
    createdAt: "2026-03-07",
    isFeatured: false,
    popularity: 80,
    topic: "述职汇报",
    dominantTone: "酒红",
    sourceType: "editorial",
  },
  {
    id: "slide-008",
    title: "销售增长数据页",
    coverImage: "business-metrics",
    category: "data",
    scenes: ["工作汇报", "商业提案"],
    tags: ["数据感", "商务蓝", "图表辅助"],
    style: "数据商务",
    summary: "突出营收与增长结论的数据摘要页，适合复盘或经营汇报。",
    layoutAnalysis: "顶部结论，底部三项关键指标卡片，右侧补充小趋势图。",
    visualFocus: "数字与百分比是第一视觉，趋势线用于辅助理解。",
    reusableTips: "结论应先于数据呈现，卡片数控制在 3 到 4 个最合适。",
    createdAt: "2026-03-08",
    isFeatured: true,
    popularity: 97,
    topic: "工作复盘",
    dominantTone: "蓝灰",
    sourceType: "editorial",
  },
  {
    id: "slide-009",
    title: "用户研究数据页",
    coverImage: "research-cards",
    category: "data",
    scenes: ["产品发布", "教育培训"],
    tags: ["极简", "中性色", "卡片式"],
    style: "研究分析",
    summary: "适合展示研究样本、关键洞察和用户分类数据。",
    layoutAnalysis: "左侧研究结论，右侧卡片分栏展示样本与指标。",
    visualFocus: "结论标题和重点百分比构成页面双核心。",
    reusableTips: "研究类页面要把样本背景和核心结论同时放进第一屏内。",
    createdAt: "2026-03-09",
    isFeatured: false,
    popularity: 79,
    topic: "产品发布",
    dominantTone: "砂岩灰",
    sourceType: "editorial",
  },
  {
    id: "slide-010",
    title: "融资核心指标页",
    coverImage: "pitch-numbers",
    category: "data",
    scenes: ["路演融资", "商业提案"],
    tags: ["深色", "高密度", "科技感"],
    style: "融资路演",
    summary: "适合呈现投资人关心的营收、用户、留存和增长指标。",
    layoutAnalysis: "顶部一句话结论，下方 4 个核心数字模块并列，底部补充趋势参考。",
    visualFocus: "核心数字字号最大，结论与增长箭头强化说服力。",
    reusableTips: "不要把整份报表搬进 PPT，优先留住最能支撑故事的三到四项指标。",
    createdAt: "2026-03-10",
    isFeatured: true,
    popularity: 98,
    topic: "路演融资",
    dominantTone: "深墨蓝",
    sourceType: "editorial",
  },
  {
    id: "slide-011",
    title: "市场份额图表页",
    coverImage: "pie-contrast",
    category: "chart",
    scenes: ["商业提案", "品牌营销"],
    tags: ["橙灰", "对比强", "图表主导"],
    style: "提案图表",
    summary: "通过环形图和条形图结合表达市场份额与品牌位置。",
    layoutAnalysis: "左图右文结构，图表保持简洁，结论写在图旁。",
    visualFocus: "高对比主色块与百分比标记建立记忆点。",
    reusableTips: "图表不要承载全部信息，结论语句必须明确写出来。",
    createdAt: "2026-03-11",
    isFeatured: false,
    popularity: 83,
    topic: "营销策划",
    dominantTone: "暖橙灰",
    sourceType: "editorial",
  },
  {
    id: "slide-012",
    title: "业务漏斗图表页",
    coverImage: "funnel-flow",
    category: "chart",
    scenes: ["工作汇报", "产品发布"],
    tags: ["极简", "蓝灰", "分析感"],
    style: "运营分析",
    summary: "适合解释转化漏斗、业务流程和关键流失环节。",
    layoutAnalysis: "左侧漏斗图，右侧用三条结论解释转化差异。",
    visualFocus: "漏斗本身是第一视觉，侧边结论负责把图变成洞察。",
    reusableTips: "漏斗越简越有效，层级不要超过 5 层。",
    createdAt: "2026-03-12",
    isFeatured: true,
    popularity: 90,
    topic: "工作复盘",
    dominantTone: "冷灰蓝",
    sourceType: "editorial",
  },
  {
    id: "slide-013",
    title: "品牌发展时间轴",
    coverImage: "timeline-editorial",
    category: "timeline",
    scenes: ["品牌营销", "商业提案"],
    tags: ["杂志感", "细线条", "留白"],
    style: "品牌叙事",
    summary: "适合讲品牌发展路径、升级节点和关键变化。",
    layoutAnalysis: "横向时间轴串联 4 个阶段，每个阶段只保留一个关键句。",
    visualFocus: "线性结构与时间节点建立清楚的阅读顺序。",
    reusableTips: "时间轴页不宜堆过多事件，宁可少放，也要让阶段关系清楚。",
    createdAt: "2026-03-13",
    isFeatured: true,
    popularity: 95,
    topic: "营销策划",
    dominantTone: "暖灰白",
    sourceType: "editorial",
  },
  {
    id: "slide-014",
    title: "项目里程碑时间轴",
    coverImage: "milestone-steps",
    category: "timeline",
    scenes: ["工作汇报", "教育培训"],
    tags: ["商务蓝", "清晰", "阶段感"],
    style: "项目管理",
    summary: "适合说明项目推进路径、阶段任务与交付节点。",
    layoutAnalysis: "纵向时间轴，左侧阶段，右侧节点说明和时间。",
    visualFocus: "节点编号让长期项目更容易被快速理解。",
    reusableTips: "当项目阶段较多时，统一节点样式比颜色区分更稳妥。",
    createdAt: "2026-03-14",
    isFeatured: false,
    popularity: 81,
    topic: "工作复盘",
    dominantTone: "淡蓝",
    sourceType: "editorial",
  },
  {
    id: "slide-015",
    title: "融资进展时间轴",
    coverImage: "venture-track",
    category: "timeline",
    scenes: ["路演融资", "产品发布"],
    tags: ["深色", "科技感", "节点式"],
    style: "融资进程",
    summary: "适合展示产品从立项到融资轮次推进的关键节点。",
    layoutAnalysis: "暗色底上采用横向节点布局，每个阶段配一条说明。",
    visualFocus: "发光节点和年份标记是整页的核心识别。",
    reusableTips: "融资和产品里程碑可以合并表达，但每个节点只说一个重点。",
    createdAt: "2026-03-15",
    isFeatured: false,
    popularity: 77,
    topic: "路演融资",
    dominantTone: "深灰紫",
    sourceType: "editorial",
  },
  {
    id: "slide-016",
    title: "改版前后对比页",
    coverImage: "before-after",
    category: "comparison",
    scenes: ["产品发布", "品牌营销"],
    tags: ["对比强", "黑白", "大图"],
    style: "改版展示",
    summary: "适合展示视觉升级、产品改版与包装更新前后差异。",
    layoutAnalysis: "左右双栏对照，上方标记 Before / After，下方保留一句变化总结。",
    visualFocus: "双图对照构成主视觉，其余内容只承担引导作用。",
    reusableTips: "要确保对比对象使用相同视角和比例，否则页面会失去说服力。",
    createdAt: "2026-03-16",
    isFeatured: true,
    popularity: 94,
    topic: "产品发布",
    dominantTone: "黑白灰",
    sourceType: "editorial",
  },
  {
    id: "slide-017",
    title: "方案优劣对比页",
    coverImage: "decision-table",
    category: "comparison",
    scenes: ["商业提案", "工作汇报"],
    tags: ["表格式", "理性", "蓝灰"],
    style: "决策说明",
    summary: "通过评分表和要点说明比较不同方案的优缺点。",
    layoutAnalysis: "表格居中，左右分区解释方案差异，底部给出推荐结论。",
    visualFocus: "推荐标记和维度评分构成主要决策信息。",
    reusableTips: "方案对比页一定要给出最终判断，不要只摆事实不下结论。",
    createdAt: "2026-03-17",
    isFeatured: false,
    popularity: 78,
    topic: "商业提案",
    dominantTone: "雾灰",
    sourceType: "editorial",
  },
  {
    id: "slide-018",
    title: "竞品对比矩阵页",
    coverImage: "matrix-map",
    category: "comparison",
    scenes: ["产品发布", "路演融资"],
    tags: ["科技感", "矩阵", "极简"],
    style: "产品策略",
    summary: "适合展示产品定位与竞品差异，强调市场空间。",
    layoutAnalysis: "四象限矩阵居中，四周用品牌标识或关键词标出典型位置。",
    visualFocus: "矩阵坐标系与目标产品所在区域构成整页记忆点。",
    reusableTips: "四象限的横纵坐标必须足够明确，否则用户难以理解定位逻辑。",
    createdAt: "2026-03-18",
    isFeatured: true,
    popularity: 92,
    topic: "路演融资",
    dominantTone: "石板蓝",
    sourceType: "editorial",
  },
  {
    id: "slide-019",
    title: "客户案例展示页",
    coverImage: "case-cards",
    category: "case-study",
    scenes: ["商业提案", "品牌营销"],
    tags: ["高级感", "卡片式", "杂志感"],
    style: "案例陈列",
    summary: "适合展示服务客户与代表案例，增强提案可信度。",
    layoutAnalysis: "三栏案例卡片陈列，每张卡片保留 logo、背景图和结果摘要。",
    visualFocus: "统一尺寸卡片和成果数字形成秩序与说服力。",
    reusableTips: "案例页优先展示结果，不要在一页里写过多背景说明。",
    createdAt: "2026-03-19",
    isFeatured: true,
    popularity: 96,
    topic: "营销策划",
    dominantTone: "奶油灰",
    sourceType: "editorial",
  },
  {
    id: "slide-020",
    title: "教学成果案例页",
    coverImage: "education-showcase",
    category: "case-study",
    scenes: ["教育培训", "毕业答辩"],
    tags: ["明亮", "结构化", "亲和"],
    style: "教育展示",
    summary: "适合展示教学成果、实践案例和课程落地效果。",
    layoutAnalysis: "左侧成果概述，右侧两到三张案例缩略图和说明。",
    visualFocus: "实拍图或案例图让页面更具真实感。",
    reusableTips: "教育案例页适合控制信息密度，让图片承担更多说服任务。",
    createdAt: "2026-03-20",
    isFeatured: false,
    popularity: 76,
    topic: "教育培训",
    dominantTone: "浅杏色",
    sourceType: "editorial",
  },
  {
    id: "slide-021",
    title: "项目复盘案例页",
    coverImage: "retrospective-notes",
    category: "case-study",
    scenes: ["工作汇报", "述职晋升"],
    tags: ["极简", "分析感", "浅灰"],
    style: "复盘说明",
    summary: "适合从目标、动作、结果三个层面复盘项目案例。",
    layoutAnalysis: "左侧目标与背景，右侧用三段卡片拆分执行动作与结果。",
    visualFocus: "三段式结构让整页逻辑很清楚，适合复盘型讲述。",
    reusableTips: "案例复盘页不要只写结果，过程拆解更能体现个人价值。",
    createdAt: "2026-03-21",
    isFeatured: false,
    popularity: 85,
    topic: "述职汇报",
    dominantTone: "浅灰",
    sourceType: "editorial",
  },
  {
    id: "slide-022",
    title: "创始人介绍页",
    coverImage: "founder-portrait",
    category: "profile",
    scenes: ["路演融资", "产品发布"],
    tags: ["深色", "人像主导", "信任感"],
    style: "团队介绍",
    summary: "适合在路演或发布场景中介绍创始人与核心背景。",
    layoutAnalysis: "左侧大人像，右侧是姓名、头衔、履历与核心亮点。",
    visualFocus: "人像和姓名构成第一视觉，对外信任感由此建立。",
    reusableTips: "人物介绍页只保留最能支撑角色可信度的经历，不要堆满简历式信息。",
    createdAt: "2026-03-22",
    isFeatured: true,
    popularity: 90,
    topic: "路演融资",
    dominantTone: "深棕灰",
    sourceType: "editorial",
  },
  {
    id: "slide-023",
    title: "讲师介绍页",
    coverImage: "mentor-card",
    category: "profile",
    scenes: ["教育培训", "毕业答辩"],
    tags: ["亲和", "明亮", "专业"],
    style: "教学讲师",
    summary: "适合展示讲师背景、研究方向和课程领域。",
    layoutAnalysis: "头像卡片和文本分栏，证书或资历用小标签呈现。",
    visualFocus: "头像与职称信息是整页的主识别点。",
    reusableTips: "讲师介绍页尽量用短句标签替代大段介绍，更适合课堂场景快速阅读。",
    createdAt: "2026-03-23",
    isFeatured: false,
    popularity: 74,
    topic: "教育培训",
    dominantTone: "浅米色",
    sourceType: "editorial",
  },
  {
    id: "slide-024",
    title: "团队核心成员页",
    coverImage: "team-grid",
    category: "profile",
    scenes: ["商业提案", "工作汇报"],
    tags: ["商务蓝", "稳重", "卡片化"],
    style: "团队展示",
    summary: "适合展示组织核心成员结构与角色分工。",
    layoutAnalysis: "网格卡片展示成员头像、角色与一行优势描述。",
    visualFocus: "统一卡片和蓝灰信息条构成稳定组织感。",
    reusableTips: "团队页核心是清楚和可信，不要用过多装饰化背景。",
    createdAt: "2026-03-24",
    isFeatured: false,
    popularity: 75,
    topic: "商业提案",
    dominantTone: "蓝灰",
    sourceType: "editorial",
  },
  {
    id: "slide-025",
    title: "述职总结结尾页",
    coverImage: "closing-statement",
    category: "ending",
    scenes: ["述职晋升", "工作汇报"],
    tags: ["极简", "留白", "一句话收束"],
    style: "汇报收尾",
    summary: "适合正式汇报结尾，以一句态度清晰的话完成收束。",
    layoutAnalysis: "页面中心一条总结语，底部保留感谢与汇报人信息。",
    visualFocus: "中心句承担全部视觉焦点，辅助信息全部弱化。",
    reusableTips: "结尾页不必重复内容目录，一句清楚的下一步方向更有效。",
    createdAt: "2026-03-25",
    isFeatured: true,
    popularity: 89,
    topic: "述职汇报",
    dominantTone: "暖白",
    sourceType: "editorial",
  },
  {
    id: "slide-026",
    title: "品牌提案结尾页",
    coverImage: "tagline-close",
    category: "ending",
    scenes: ["品牌营销", "商业提案"],
    tags: ["黑白灰", "高级感", "标语式"],
    style: "提案收尾",
    summary: "通过一句品牌态度或提案结论收束完整提案。",
    layoutAnalysis: "大字号标语置中，底部是一行联系或致谢信息。",
    visualFocus: "标语的字重、字距和留白是页面气质的关键。",
    reusableTips: "提案结尾页要像一句结论而不是一段说明，越短越有力量。",
    createdAt: "2026-03-26",
    isFeatured: false,
    popularity: 80,
    topic: "营销策划",
    dominantTone: "灰白",
    sourceType: "editorial",
  },
  {
    id: "slide-027",
    title: "答辩致谢页",
    coverImage: "thanks-light",
    category: "ending",
    scenes: ["毕业答辩", "教育培训"],
    tags: ["明亮", "轻设计", "简洁"],
    style: "答辩结尾",
    summary: "适合毕业答辩或课程结尾，以礼貌和清晰完成结束。",
    layoutAnalysis: "标题居中，下方保留简短感谢与答辩信息。",
    visualFocus: "致谢标题和轻量线性装饰形成适度仪式感。",
    reusableTips: "答辩结尾页不要加入额外信息，保持干净更显专业。",
    createdAt: "2026-03-27",
    isFeatured: false,
    popularity: 72,
    topic: "毕业答辩",
    dominantTone: "浅象牙白",
    sourceType: "editorial",
  },
  {
    id: "slide-028",
    title: "校园项目封面",
    coverImage: "campus-cover",
    category: "cover",
    scenes: ["毕业答辩", "教育培训"],
    tags: ["清爽", "中性色", "版式规整"],
    style: "学术展示",
    summary: "适合毕业设计、课程答辩和学术项目展示。",
    layoutAnalysis: "中部标题配副标题，下方以细线和项目说明构成学术秩序。",
    visualFocus: "标题层级和规整版式让页面显得更可信。",
    reusableTips: "学术型封面不需要复杂装饰，信息准确和版式稳定更重要。",
    createdAt: "2026-03-28",
    isFeatured: false,
    popularity: 73,
    topic: "毕业答辩",
    dominantTone: "米白",
    sourceType: "editorial",
  },
  {
    id: "slide-029",
    title: "新品卖点图表页",
    coverImage: "launch-bars",
    category: "chart",
    scenes: ["产品发布", "品牌营销"],
    tags: ["高对比", "色块", "重点突出"],
    style: "营销发布",
    summary: "适合发布会和新品提案场景，用图表快速说明卖点优势。",
    layoutAnalysis: "左侧产品图或卖点标题，右侧条形图和三条亮点说明。",
    visualFocus: "高对比色块让关键卖点在远距离也能被看到。",
    reusableTips: "发布类图表页要优先服务表达，不要做成复杂分析图。",
    createdAt: "2026-03-29",
    isFeatured: true,
    popularity: 87,
    topic: "产品发布",
    dominantTone: "炭黑橙",
    sourceType: "editorial",
  },
  {
    id: "slide-030",
    title: "培训课程目录页",
    coverImage: "course-columns",
    category: "agenda",
    scenes: ["教育培训", "产品发布"],
    tags: ["极简", "分栏", "清晰"],
    style: "教学结构",
    summary: "适合课程大纲和培训模块导览，帮助学员快速理解结构。",
    layoutAnalysis: "双栏或三栏模块展示课程章节与课时信息。",
    visualFocus: "分栏结构和统一编号增强阅读效率。",
    reusableTips: "培训目录页优先保持逻辑清楚，模块标题建议统一为动宾短语。",
    createdAt: "2026-03-30",
    isFeatured: false,
    popularity: 71,
    topic: "教育培训",
    dominantTone: "浅灰蓝",
    sourceType: "editorial",
  },
];

export const initialCollections: Collection[] = [
  {
    id: "collection-default",
    name: "默认收藏",
    slideIds: ["slide-001", "slide-019", "slide-025"],
    createdAt: "2026-03-01",
    updatedAt: "2026-03-25",
  },
  {
    id: "collection-q2-report",
    name: "Q2述职参考",
    slideIds: ["slide-004", "slide-008", "slide-025"],
    createdAt: "2026-03-05",
    updatedAt: "2026-03-25",
  },
  {
    id: "collection-brand-proposal",
    name: "品牌提案参考",
    slideIds: ["slide-002", "slide-013", "slide-019", "slide-026"],
    createdAt: "2026-03-10",
    updatedAt: "2026-03-26",
  },
];
