import { Collection, Slide } from "@/lib/types";

export const slides: Slide[] = [
  {
    id: "slide-001",
    title: "整页案例介绍",
    coverImage: "/images/slides/slide-001.jpg",
    category: "cover",
    scenes: ["述职晋升", "工作汇报"],
    tags: ["深色", "高级感"],
    style: "色彩丰富",
    summary: "适合年度述职与管理层汇报的封面页，以大标题和氛围视觉建立正式感。",
    layoutAnalysis: "左侧大标题配信息栏，右侧保留深色建筑或人物氛围图，底部收纳时间和汇报人信息。",
    visualFocus: "标题与深色背景形成强对比，留白让主标题具备更高权重。",
    reusableTips: "封面页只保留最关键标题、身份和日期，用一张高质背景图建立情绪即可。",
    createdAt: "2026-03-01",
    isFeatured: true,
    popularity: 96,
    topic: "述职汇报",
    dominantTone: "深海蓝",
    sourceType: "editorial",
  },
  {
    id: "slide-002",
    title: "极简品牌提案封面",
    coverImage: "/images/slides/slide-002.jpg",
    category: "cover",
    scenes: ["品牌营销", "商业提案"],
    tags: ["极简", "留白", "黑白灰"],
    style: "极简编辑感",
    summary: "以大留白和精炼标题构成的提案封面，适合品牌与策略类内容。",
    layoutAnalysis: "中心对齐标题搭配细线分割，下方保留提案对象与日期信息。",
    visualFocus: "留白本身就是视觉秩序，文本被精确控制在小范围内。",
    reusableTips: "标题控制在 8 到 12 字内，副标题保持中性色，不要抢主标题。",
    createdAt: "2026-03-02",
    isFeatured: true,
    popularity: 91,
    topic: "营销策划",
    dominantTone: "暖白",
    sourceType: "editorial",
  },
  {
    id: "slide-003",
    title: "路演融资数据封面",
    coverImage: "/images/slides/slide-003.jpg",
    category: "cover",
    scenes: ["路演融资", "产品发布"],
    tags: ["科技感", "深色", "几何"],
    style: "科技简报",
    summary: "用几何线条与高对比数字构成的路演封面，适合科技产品叙事。",
    layoutAnalysis: "上部品牌名与轮次信息，下部标题，背景通过网格和斜线加强未来感。",
    visualFocus: "主标题与右上角关键轮次信息形成双锚点。",
    reusableTips: "融资封面要强调核心身份信息，视觉元素控制在几何与品牌色范围内。",
    createdAt: "2026-03-03",
    isFeatured: true,
    popularity: 84,
    topic: "路演融资",
    dominantTone: "石墨黑",
    sourceType: "editorial",
  },
  {
    id: "slide-004",
    title: "季度复盘目录页",
    coverImage: "/images/slides/slide-004.jpg",
    category: "agenda",
    scenes: ["工作汇报", "述职晋升"],
    tags: ["极简", "商务蓝", "结构清晰"],
    style: "理性商务",
    summary: "适合季度和年度复盘的目录页，突出章节顺序与阅读路径。",
    layoutAnalysis: "顶部标题，下方四栏等宽模块排列，采用数字编号和短句章节名。",
    visualFocus: "连续编号和规整对齐制造稳定节奏。",
    reusableTips: "目录页不要塞满说明，用短标题和统一编号建立秩序即可。",
    createdAt: "2026-03-04",
    isFeatured: true,
    popularity: 93,
    topic: "工作复盘",
    dominantTone: "雾蓝灰",
    sourceType: "editorial",
  },
  {
    id: "slide-005",
    title: "品牌策略目录页",
    coverImage: "/images/slides/slide-005.png",
    category: "agenda",
    scenes: ["品牌营销", "商业提案"],
    tags: ["杂志感", "高对比", "留白"],
    style: "编辑策划",
    summary: "适合品牌策略与整合营销提案，用类似目录编排增强策展感。",
    layoutAnalysis: "左侧大编号，右侧多行章节目录，辅以细线和页码式装饰。",
    visualFocus: "大编号让整页拥有强识别点，目录文本形成次级层次。",
    reusableTips: "当目录内容较多时，优先强化编号系统，文本字重保持统一。",
    createdAt: "2026-03-05",
    isFeatured: false,
    popularity: 82,
    topic: "营销策划",
    dominantTone: "奶油白",
    sourceType: "editorial",
  },
  {
    id: "slide-006",
    title: "产品发布章节过渡",
    coverImage: "/images/slides/slide-006.webp",
    category: "transition",
    scenes: ["产品发布", "教育培训"],
    tags: ["深色", "大字标题", "科技感"],
    style: "发布会风格",
    summary: "章节切换时使用的强标题过渡页，适合产品发布节奏。",
    layoutAnalysis: "整页只保留章节标题与极少辅助字，背景使用大面积深色渐变。",
    visualFocus: "超大字号与深色背景形成明显停顿感。",
    reusableTips: "过渡页只做一件事，就是让下一段内容被清楚感知，不要加入过多信息。",
    createdAt: "2026-03-06",
    isFeatured: true,
    popularity: 88,
    topic: "产品发布",
    dominantTone: "炭黑",
    sourceType: "editorial",
  },
  {
    id: "slide-007",
    title: "年终总结章节过渡",
    coverImage: "/images/slides/slide-007.png",
    category: "transition",
    scenes: ["工作汇报", "述职晋升"],
    tags: ["红黑", "强标题", "仪式感"],
    style: "总结汇报",
    summary: "用于年终汇报章节切换，强调节点感与正式氛围。",
    layoutAnalysis: "中心标题搭配年份编号和细线，背景使用低透明纹理增加层次。",
    visualFocus: "大标题和年份形成纪念性视觉焦点。",
    reusableTips: "过渡页适合放年份、阶段、主题词，不建议放解释性长文。",
    createdAt: "2026-03-07",
    isFeatured: false,
    popularity: 80,
    topic: "述职汇报",
    dominantTone: "酒红",
    sourceType: "editorial",
  },
  {
    id: "slide-008",
    title: "销售增长数据页",
    coverImage: "/images/slides/slide-008.jpg",
    category: "data",
    scenes: ["工作汇报", "商业提案"],
    tags: ["数据感", "商务蓝", "图表辅助"],
    style: "数据商务",
    summary: "突出营收与增长结论的数据摘要页，适合复盘或经营汇报。",
    layoutAnalysis: "顶部结论，底部三项关键指标卡片，右侧补充小趋势图。",
    visualFocus: "数字与百分比是第一视觉，趋势线用于辅助理解。",
    reusableTips: "结论应先于数据呈现，卡片数控制在 3 到 4 个最合适。",
    createdAt: "2026-03-08",
    isFeatured: true,
    popularity: 97,
    topic: "工作复盘",
    dominantTone: "蓝灰",
    sourceType: "editorial",
  },
  {
    id: "slide-009",
    title: "用户研究数据页",
    coverImage: "/images/slides/slide-009.jpg",
    category: "data",
    scenes: ["产品发布", "教育培训"],
    tags: ["极简", "中性色", "卡片式"],
    style: "研究分析",
    summary: "适合展示研究样本、关键洞察和用户分类数据。",
    layoutAnalysis: "左侧研究结论，右侧卡片分栏展示样本与指标。",
    visualFocus: "结论标题和重点百分比构成页面双核心。",
    reusableTips: "研究类页面要把样本背景和核心结论同时放进第一屏内。",
    createdAt: "2026-03-09",
    isFeatured: false,
    popularity: 79,
    topic: "产品发布",
    dominantTone: "砂岩灰",
    sourceType: "editorial",
  },
  {
    id: "slide-010",
    title: "融资核心指标页",
    coverImage: "/images/slides/slide-010.jpg",
    category: "data",
    scenes: ["路演融资", "商业提案"],
    tags: ["深色", "高密度", "科技感"],
    style: "融资路演",
    summary: "适合呈现投资人关心的营收、用户、留存和增长指标。",
    layoutAnalysis: "顶部一句话结论，下方 4 个核心数字模块并列，底部补充趋势参考。",
    visualFocus: "核心数字字号最大，结论与增长箭头强化说服力。",
    reusableTips: "不要把整份报表搬进 PPT，优先留住最能支撑故事的三到四项指标。",
    createdAt: "2026-03-10",
    isFeatured: true,
    popularity: 98,
    topic: "路演融资",
    dominantTone: "深墨蓝",
    sourceType: "editorial",
  },
  {
    id: "slide-011",
    title: "市场份额图表页",
    coverImage: "/images/slides/slide-011.png",
    category: "chart",
    scenes: ["商业提案", "品牌营销"],
    tags: ["橙灰", "对比强", "图表主导"],
    style: "提案图表",
    summary: "通过环形图和条形图结合表达市场份额与品牌位置。",
    layoutAnalysis: "左图右文结构，图表保持简洁，结论写在图旁。",
    visualFocus: "高对比主色块与百分比标记建立记忆点。",
    reusableTips: "图表不要承载全部信息，结论语句必须明确写出来。",
    createdAt: "2026-03-11",
    isFeatured: false,
    popularity: 83,
    topic: "营销策划",
    dominantTone: "暖橙灰",
    sourceType: "editorial",
  },
  {
    id: "slide-012",
    title: "业务漏斗图表页",
    coverImage: "/images/slides/slide-012.jpg",
    category: "chart",
    scenes: ["工作汇报", "产品发布"],
    tags: ["极简", "蓝灰", "分析感"],
    style: "运营分析",
    summary: "适合解释转化漏斗、业务流程和关键流失环节。",
    layoutAnalysis: "左侧漏斗图，右侧用三条结论解释转化差异。",
    visualFocus: "漏斗本身是第一视觉，侧边结论负责把图变成洞察。",
    reusableTips: "漏斗越简越有效，层级不要超过 5 层。",
    createdAt: "2026-03-12",
    isFeatured: true,
    popularity: 90,
    topic: "工作复盘",
    dominantTone: "冷灰蓝",
    sourceType: "editorial",
  },
  {
    id: "slide-013",
    title: "品牌发展时间轴",
    coverImage: "/images/slides/slide-013.png",
    category: "timeline",
    scenes: ["品牌营销", "商业提案"],
    tags: ["杂志感", "细线条", "留白"],
    style: "品牌叙事",
    summary: "适合讲品牌发展路径、升级节点和关键变化。",
    layoutAnalysis: "横向时间轴串联 4 个阶段，每个阶段只保留一个关键句。",
    visualFocus: "线性结构与时间节点建立清楚的阅读顺序。",
    reusableTips: "时间轴页不宜堆过多事件，宁可少放，也要让阶段关系清楚。",
    createdAt: "2026-03-13",
    isFeatured: true,
    popularity: 95,
    topic: "营销策划",
    dominantTone: "暖灰白",
    sourceType: "editorial",
  },
  {
    id: "slide-014",
    title: "项目里程碑时间轴",
    coverImage: "/images/slides/slide-014.png",
    category: "timeline",
    scenes: ["工作汇报", "教育培训"],
    tags: ["商务蓝", "清晰", "阶段感"],
    style: "项目管理",
    summary: "适合说明项目推进路径、阶段任务与交付节点。",
    layoutAnalysis: "纵向时间轴，左侧阶段，右侧节点说明和时间。",
    visualFocus: "节点编号让长期项目更容易被快速理解。",
    reusableTips: "当项目阶段较多时，统一节点样式比颜色区分更稳妥。",
    createdAt: "2026-03-14",
    isFeatured: false,
    popularity: 81,
    topic: "工作复盘",
    dominantTone: "淡蓝",
    sourceType: "editorial",
  },
  {
    id: "slide-015",
    title: "融资进展时间轴",
    coverImage: "/images/slides/slide-015.png",
    category: "timeline",
    scenes: ["路演融资", "产品发布"],
    tags: ["深色", "科技感", "节点式"],
    style: "融资进程",
    summary: "适合展示产品从立项到融资轮次推进的关键节点。",
    layoutAnalysis: "暗色底上采用横向节点布局，每个阶段配一条说明。",
    visualFocus: "发光节点和年份标记是整页的核心识别。",
    reusableTips: "融资和产品里程碑可以合并表达，但每个节点只说一个重点。",
    createdAt: "2026-03-15",
    isFeatured: false,
    popularity: 77,
    topic: "路演融资",
    dominantTone: "深灰紫",
    sourceType: "editorial",
  },
  {
    id: "slide-016",
    title: "改版前后对比页",
    coverImage: "/images/slides/slide-016.png",
    category: "comparison",
    scenes: ["产品发布", "品牌营销"],
    tags: ["对比强", "黑白", "大图"],
    style: "改版展示",
    summary: "适合展示视觉升级、产品改版与包装更新前后差异。",
    layoutAnalysis: "左右双栏对照，上方标记 Before / After，下方保留一句变化总结。",
    visualFocus: "双图对照构成主视觉，其余内容只承担引导作用。",
    reusableTips: "要确保对比对象使用相同视角和比例，否则页面会失去说服力。",
    createdAt: "2026-03-16",
    isFeatured: true,
    popularity: 94,
    topic: "产品发布",
    dominantTone: "黑白灰",
    sourceType: "editorial",
  },
  {
    id: "slide-017",
    title: "方案优劣对比页",
    coverImage: "/images/slides/slide-017.jpg",
    category: "comparison",
    scenes: ["商业提案", "工作汇报"],
    tags: ["表格式", "理性", "蓝灰"],
    style: "决策说明",
    summary: "通过评分表和要点说明比较不同方案的优缺点。",
    layoutAnalysis: "表格居中，左右分区解释方案差异，底部给出推荐结论。",
    visualFocus: "推荐标记和维度评分构成主要决策信息。",
    reusableTips: "方案对比页一定要给出最终判断，不要只摆事实不下结论。",
    createdAt: "2026-03-17",
    isFeatured: false,
    popularity: 78,
    topic: "商业提案",
    dominantTone: "雾灰",
    sourceType: "editorial",
  },
  {
    id: "slide-018",
    title: "竞品对比矩阵页",
    coverImage: "/images/slides/slide-018.jpg",
    category: "comparison",
    scenes: ["产品发布", "路演融资"],
    tags: ["科技感", "矩阵", "极简"],
    style: "产品策略",
    summary: "适合展示产品定位与竞品差异，强调市场空间。",
    layoutAnalysis: "四象限矩阵居中，四周用品牌标识或关键词标出典型位置。",
    visualFocus: "矩阵坐标系与目标产品所在区域构成整页记忆点。",
    reusableTips: "四象限的横纵坐标必须足够明确，否则用户难以理解定位逻辑。",
    createdAt: "2026-03-18",
    isFeatured: true,
    popularity: 92,
    topic: "路演融资",
    dominantTone: "石板蓝",
    sourceType: "editorial",
  },
  {
    id: "slide-019",
    title: "客户案例展示页",
    coverImage: "/images/slides/slide-019.jpg",
    category: "case-study",
    scenes: ["商业提案", "品牌营销"],
    tags: ["高级感", "卡片式", "杂志感"],
    style: "案例陈列",
    summary: "适合展示服务客户与代表案例，增强提案可信度。",
    layoutAnalysis: "三栏案例卡片陈列，每张卡片保留 logo、背景图和结果摘要。",
    visualFocus: "统一尺寸卡片和成果数字形成秩序与说服力。",
    reusableTips: "案例页优先展示结果，不要在一页里写过多背景说明。",
    createdAt: "2026-03-19",
    isFeatured: true,
    popularity: 96,
    topic: "营销策划",
    dominantTone: "奶油灰",
    sourceType: "editorial",
  },
  {
    id: "slide-020",
    title: "教学成果案例页",
    coverImage: "/images/slides/slide-020.jpg",
    category: "case-study",
    scenes: ["教育培训", "毕业答辩"],
    tags: ["明亮", "结构化", "亲和"],
    style: "教育展示",
    summary: "适合展示教学成果、实践案例和课程落地效果。",
    layoutAnalysis: "左侧成果概述，右侧两到三张案例缩略图和说明。",
    visualFocus: "实拍图或案例图让页面更具真实感。",
    reusableTips: "教育案例页适合控制信息密度，让图片承担更多说服任务。",
    createdAt: "2026-03-20",
    isFeatured: false,
    popularity: 76,
    topic: "教育培训",
    dominantTone: "浅杏色",
    sourceType: "editorial",
  },
  {
    id: "slide-021",
    title: "项目复盘案例页",
    coverImage: "/images/slides/slide-021.jpg",
    category: "case-study",
    scenes: ["工作汇报", "述职晋升"],
    tags: ["极简", "分析感", "浅灰"],
    style: "复盘说明",
    summary: "适合从目标、动作、结果三个层面复盘项目案例。",
    layoutAnalysis: "左侧目标与背景，右侧用三段卡片拆分执行动作与结果。",
    visualFocus: "三段式结构让整页逻辑很清楚，适合复盘型讲述。",
    reusableTips: "案例复盘页不要只写结果，过程拆解更能体现个人价值。",
    createdAt: "2026-03-21",
    isFeatured: false,
    popularity: 85,
    topic: "述职汇报",
    dominantTone: "浅灰",
    sourceType: "editorial",
  },
  {
    id: "slide-022",
    title: "创始人介绍页",
    coverImage: "/images/slides/slide-022.png",
    category: "profile",
    scenes: ["路演融资", "产品发布"],
    tags: ["深色", "人像主导", "信任感"],
    style: "团队介绍",
    summary: "适合在路演或发布场景中介绍创始人与核心背景。",
    layoutAnalysis: "左侧大人像，右侧是姓名、头衔、履历与核心亮点。",
    visualFocus: "人像和姓名构成第一视觉，对外信任感由此建立。",
    reusableTips: "人物介绍页只保留最能支撑角色可信度的经历，不要堆满简历式信息。",
    createdAt: "2026-03-22",
    isFeatured: true,
    popularity: 90,
    topic: "路演融资",
    dominantTone: "深棕灰",
    sourceType: "editorial",
  },
  {
    id: "slide-023",
    title: "讲师介绍页",
    coverImage: "/images/slides/slide-023.jpg",
    category: "profile",
    scenes: ["教育培训", "毕业答辩"],
    tags: ["亲和", "明亮", "专业"],
    style: "教学讲师",
    summary: "适合展示讲师背景、研究方向和课程领域。",
    layoutAnalysis: "头像卡片和文本分栏，证书或资历用小标签呈现。",
    visualFocus: "头像与职称信息是整页的主识别点。",
    reusableTips: "讲师介绍页尽量用短句标签替代大段介绍，更适合课堂场景快速阅读。",
    createdAt: "2026-03-23",
    isFeatured: false,
    popularity: 74,
    topic: "教育培训",
    dominantTone: "浅米色",
    sourceType: "editorial",
  },
  {
    id: "slide-024",
    title: "团队核心成员页",
    coverImage: "/images/slides/slide-024.jpg",
    category: "profile",
    scenes: ["商业提案", "工作汇报"],
    tags: ["商务蓝", "稳重", "卡片化"],
    style: "团队展示",
    summary: "适合展示组织核心成员结构与角色分工。",
    layoutAnalysis: "网格卡片展示成员头像、角色与一行优势描述。",
    visualFocus: "统一卡片和蓝灰信息条构成稳定组织感。",
    reusableTips: "团队页核心是清楚和可信，不要用过多装饰化背景。",
    createdAt: "2026-03-24",
    isFeatured: false,
    popularity: 75,
    topic: "商业提案",
    dominantTone: "蓝灰",
    sourceType: "editorial",
  },
  {
    id: "slide-025",
    title: "述职总结结尾页",
    coverImage: "/images/slides/slide-025.jpg",
    category: "ending",
    scenes: ["述职晋升", "工作汇报"],
    tags: ["极简", "留白", "一句话收束"],
    style: "汇报收尾",
    summary: "适合正式汇报结尾，以一句态度清晰的话完成收束。",
    layoutAnalysis: "页面中心一条总结语，底部保留感谢与汇报人信息。",
    visualFocus: "中心句承担全部视觉焦点，辅助信息全部弱化。",
    reusableTips: "结尾页不必重复内容目录，一句清楚的下一步方向更有效。",
    createdAt: "2026-03-25",
    isFeatured: true,
    popularity: 89,
    topic: "述职汇报",
    dominantTone: "暖白",
    sourceType: "editorial",
  },
  {
    id: "slide-026",
    title: "品牌提案结尾页",
    coverImage: "/images/slides/slide-026.png",
    category: "ending",
    scenes: ["品牌营销", "商业提案"],
    tags: ["黑白灰", "高级感", "标语式"],
    style: "提案收尾",
    summary: "通过一句品牌态度或提案结论收束完整提案。",
    layoutAnalysis: "大字号标语置中，底部是一行联系或致谢信息。",
    visualFocus: "标语的字重、字距和留白是页面气质的关键。",
    reusableTips: "提案结尾页要像一句结论而不是一段说明，越短越有力量。",
    createdAt: "2026-03-26",
    isFeatured: false,
    popularity: 80,
    topic: "营销策划",
    dominantTone: "灰白",
    sourceType: "editorial",
  },
  {
    id: "slide-027",
    title: "答辩致谢页",
    coverImage: "/images/slides/slide-027.jpg",
    category: "ending",
    scenes: ["毕业答辩", "教育培训"],
    tags: ["明亮", "轻设计", "简洁"],
    style: "答辩结尾",
    summary: "适合毕业答辩或课程结尾，以礼貌和清晰完成结束。",
    layoutAnalysis: "标题居中，下方保留简短感谢与答辩信息。",
    visualFocus: "致谢标题和轻量线性装饰形成适度仪式感。",
    reusableTips: "答辩结尾页不要加入额外信息，保持干净更显专业。",
    createdAt: "2026-03-27",
    isFeatured: false,
    popularity: 72,
    topic: "毕业答辩",
    dominantTone: "浅象牙白",
    sourceType: "editorial",
  },
  {
    id: "slide-028",
    title: "校园项目封面",
    coverImage: "/images/slides/slide-028.jpg",
    category: "cover",
    scenes: ["毕业答辩", "教育培训"],
    tags: ["清爽", "中性色", "版式规整"],
    style: "学术展示",
    summary: "适合毕业设计、课程答辩和学术项目展示。",
    layoutAnalysis: "中部标题配副标题，下方以细线和项目说明构成学术秩序。",
    visualFocus: "标题层级和规整版式让页面显得更可信。",
    reusableTips: "学术型封面不需要复杂装饰，信息准确和版式稳定更重要。",
    createdAt: "2026-03-28",
    isFeatured: false,
    popularity: 73,
    topic: "毕业答辩",
    dominantTone: "米白",
    sourceType: "editorial",
  },
  {
    id: "slide-029",
    title: "新品卖点图表页",
    coverImage: "/images/slides/slide-029.jpg",
    category: "chart",
    scenes: ["产品发布", "品牌营销"],
    tags: ["高对比", "色块", "重点突出"],
    style: "营销发布",
    summary: "适合发布会和新品提案场景，用图表快速说明卖点优势。",
    layoutAnalysis: "左侧产品图或卖点标题，右侧条形图和三条亮点说明。",
    visualFocus: "高对比色块让关键卖点在远距离也能被看到。",
    reusableTips: "发布类图表页要优先服务表达，不要做成复杂分析图。",
    createdAt: "2026-03-29",
    isFeatured: true,
    popularity: 87,
    topic: "产品发布",
    dominantTone: "炭黑橙",
    sourceType: "editorial",
  },
  {
    id: "slide-030",
    title: "培训课程目录页",
    coverImage: "/images/slides/slide-030.webp",
    category: "agenda",
    scenes: ["教育培训", "产品发布"],
    tags: ["极简", "分栏", "清晰"],
    style: "教学结构",
    summary: "适合课程大纲和培训模块导览，帮助学员快速理解结构。",
    layoutAnalysis: "双栏或三栏模块展示课程章节与课时信息。",
    visualFocus: "分栏结构和统一编号增强阅读效率。",
    reusableTips: "培训目录页优先保持逻辑清楚，模块标题建议统一为动宾短语。",
    createdAt: "2026-03-30",
    isFeatured: false,
    popularity: 71,
    topic: "教育培训",
    dominantTone: "浅灰蓝",
    sourceType: "editorial",
  },
  {
    id: "slide-031",
    title: "运动品牌海报页",
    coverImage: "/images/slides/slide-031.jpg",
    category: "cover",
    scenes: ["品牌营销", "产品发布"],
    tags: ["品牌视觉", "海报感", "动势"],
    style: "广告主视觉",
    summary: "适合品牌 Campaign、联名发布和新品预热的高视觉冲击封面页。",
    layoutAnalysis: "以单张主视觉承担注意力，文字信息压缩在局部区域，维持强画面感。",
    visualFocus: "主体产品或人物作为第一焦点，标题和品牌信息作为第二层级。",
    reusableTips: "这类页面不要塞太多说明，把信息量控制在标题和一句辅助文案内。",
    createdAt: "2026-03-31",
    isFeatured: true,
    popularity: 88,
    topic: "品牌视觉",
    dominantTone: "运动亮色",
    sourceType: "editorial",
  },
  {
    id: "slide-032",
    title: "赛事胜利封面页",
    coverImage: "/images/slides/slide-032.png",
    category: "cover",
    scenes: ["品牌营销", "工作汇报"],
    tags: ["高对比", "海报感", "电竞视觉"],
    style: "事件传播",
    summary: "适合活动节点、赛事结果和品牌战报传播的强情绪封面页。",
    layoutAnalysis: "大面积主视觉搭配极少量关键信息，突出结果和情绪价值。",
    visualFocus: "标题和核心图像形成双锚点，用户会先记住情绪再记住信息。",
    reusableTips: "结果类页面适合用极少文字，重点是把情绪做满而不是写满。",
    createdAt: "2026-04-01",
    isFeatured: false,
    popularity: 84,
    topic: "活动战报",
    dominantTone: "黑红",
    sourceType: "editorial",
  },
  {
    id: "slide-033",
    title: "动漫致敬海报页",
    coverImage: "/images/slides/slide-033.png",
    category: "cover",
    scenes: ["品牌营销", "商业提案"],
    tags: ["插画感", "IP气质", "高辨识"],
    style: "视觉概念",
    summary: "适合概念提案、视觉风格展示和 IP 方向情绪页。",
    layoutAnalysis: "整页以图形或角色做核心识别，标题与辅助字保持克制。",
    visualFocus: "角色或海报主体决定页面记忆点，其余信息只做辅助。",
    reusableTips: "视觉概念页最怕信息太碎，宁可只保留主题词也不要破坏完整气质。",
    createdAt: "2026-04-02",
    isFeatured: false,
    popularity: 79,
    topic: "视觉概念",
    dominantTone: "深紫黑",
    sourceType: "editorial",
  },
  {
    id: "slide-034",
    title: "汽车广告主视觉页",
    coverImage: "/images/slides/slide-034.jpg",
    category: "cover",
    scenes: ["品牌营销", "产品发布"],
    tags: ["汽车", "大片感", "高级感"],
    style: "品牌大片",
    summary: "适合汽车、科技硬件和高客单产品的主视觉封面展示。",
    layoutAnalysis: "用大图建立高端感，文字放在不打扰产品主体的位置。",
    visualFocus: "产品本体是绝对视觉中心，背景环境负责建立氛围。",
    reusableTips: "高端主视觉页要避免标签化元素过多，让产品自己说话。",
    createdAt: "2026-04-03",
    isFeatured: true,
    popularity: 91,
    topic: "产品视觉",
    dominantTone: "深灰",
    sourceType: "editorial",
  },
  {
    id: "slide-035",
    title: "人物海报封面页",
    coverImage: "/images/slides/slide-035.jpg",
    category: "profile",
    scenes: ["商业提案", "品牌营销"],
    tags: ["人像", "封面感", "情绪化"],
    style: "人物视觉",
    summary: "适合主理人、代言人或角色设定相关的人物主视觉页。",
    layoutAnalysis: "人物大图占据主要画面，信息通过少量文案做身份标注。",
    visualFocus: "人像和标题是同级重点，适合建立人物记忆点。",
    reusableTips: "人像页尽量控制文案长度，避免破坏人物视线和构图。",
    createdAt: "2026-04-04",
    isFeatured: false,
    popularity: 77,
    topic: "人物展示",
    dominantTone: "中性灰",
    sourceType: "editorial",
  },
  {
    id: "slide-036",
    title: "横幅广告灵感页",
    coverImage: "/images/slides/slide-036.jpg",
    category: "cover",
    scenes: ["品牌营销", "商业提案"],
    tags: ["Banner", "促销感", "图文结合"],
    style: "营销横幅",
    summary: "适合做广告横幅、活动 KV 和线上传播物料参考。",
    layoutAnalysis: "画面会把主卖点、产品图和 CTA 聚焦在一条清晰路径上。",
    visualFocus: "标题和主商品形成第一层，按钮或利益点形成第二层。",
    reusableTips: "横幅型页面要尽量保证阅读路径单一，不要让多个焦点打架。",
    createdAt: "2026-04-05",
    isFeatured: false,
    popularity: 82,
    topic: "营销传播",
    dominantTone: "高对比亮色",
    sourceType: "editorial",
  },
  {
    id: "slide-037",
    title: "创意品牌封面页",
    coverImage: "/images/slides/slide-037.jpg",
    category: "cover",
    scenes: ["品牌营销", "商业提案"],
    tags: ["创意感", "排版实验", "品牌页"],
    style: "创意提案",
    summary: "适合品牌概念页、主视觉风格页和创意方向提案。",
    layoutAnalysis: "通过夸张构图、字体和图形建立差异化审美。",
    visualFocus: "风格本身就是信息，画面语言比文字更重要。",
    reusableTips: "创意型页面建议控制说明文字，避免把它做成普通介绍页。",
    createdAt: "2026-04-06",
    isFeatured: false,
    popularity: 80,
    topic: "品牌提案",
    dominantTone: "多彩",
    sourceType: "editorial",
  },
  {
    id: "slide-038",
    title: "星座主题视觉页",
    coverImage: "/images/slides/slide-038.jpg",
    category: "case-study",
    scenes: ["品牌营销", "教育培训"],
    tags: ["主题化", "插画感", "轻内容"],
    style: "内容专题",
    summary: "适合专题内容、栏目企划和轻量品牌内容展示。",
    layoutAnalysis: "以主题插画或图形为主，文本负责点明栏目主题。",
    visualFocus: "主题图形先建立氛围，标题再完成识别。",
    reusableTips: "主题页适合做轻一点，信息不宜压过画面氛围。",
    createdAt: "2026-04-07",
    isFeatured: false,
    popularity: 74,
    topic: "专题企划",
    dominantTone: "梦幻紫",
    sourceType: "editorial",
  },
  {
    id: "slide-039",
    title: "Agency 提案封面页",
    coverImage: "/images/slides/slide-039.jpg",
    category: "cover",
    scenes: ["商业提案", "品牌营销"],
    tags: ["Agency", "高级感", "极简"],
    style: "机构提案",
    summary: "适合策略公司、设计公司和品牌机构的提案封面展示。",
    layoutAnalysis: "整体偏克制，依赖留白、对齐和局部材质建立专业感。",
    visualFocus: "机构名和主标题构成秩序感，细节材质增强精致度。",
    reusableTips: "机构提案封面越克制越显专业，不要用太多装饰抢走信任感。",
    createdAt: "2026-04-08",
    isFeatured: true,
    popularity: 86,
    topic: "机构提案",
    dominantTone: "黑白灰",
    sourceType: "editorial",
  },
  {
    id: "slide-040",
    title: "作品集展示封面页",
    coverImage: "/images/slides/slide-040.jpg",
    category: "profile",
    scenes: ["商业提案", "毕业答辩"],
    tags: ["Portfolio", "展示感", "作品陈列"],
    style: "作品集封面",
    summary: "适合作品集开篇、个人展示和案例陈列类封面页。",
    layoutAnalysis: "强调作者身份和作品调性，文字只承担必要说明。",
    visualFocus: "主视觉与姓名或项目名共同建立个人品牌印象。",
    reusableTips: "作品集封面不要把项目目录塞进来，先建立气质更重要。",
    createdAt: "2026-04-09",
    isFeatured: true,
    popularity: 90,
    topic: "作品集",
    dominantTone: "纯白",
    sourceType: "editorial",
  },
  {
    id: "slide-041",
    title: "落日氛围海报页",
    coverImage: "/images/slides/slide-041.png",
    category: "cover",
    scenes: ["品牌营销", "商业提案"],
    tags: ["氛围图", "暖色", "情绪化"],
    style: "情绪海报",
    summary: "适合情绪板、品牌调性表达和氛围封面展示。",
    layoutAnalysis: "通过单张氛围视觉配合短标题完成调性传达。",
    visualFocus: "颜色和氛围先打动用户，文字做最少量识别。",
    reusableTips: "情绪型页面适合少字，不要把它变成说明页。",
    createdAt: "2026-04-10",
    isFeatured: false,
    popularity: 76,
    topic: "情绪板",
    dominantTone: "暖橙粉",
    sourceType: "editorial",
  },
  {
    id: "slide-042",
    title: "矢量插画封面页",
    coverImage: "/images/slides/slide-042.jpg",
    category: "cover",
    scenes: ["教育培训", "产品发布"],
    tags: ["插画", "轻量", "亲和"],
    style: "插画主视觉",
    summary: "适合轻产品、课程内容和面向大众的友好型封面页。",
    layoutAnalysis: "插画承担主要叙事，文字和按钮信息控制在局部。",
    visualFocus: "插画主体负责吸睛，标题负责快速定主题。",
    reusableTips: "插画页要避免信息密度太高，让画面保持轻盈。",
    createdAt: "2026-04-11",
    isFeatured: false,
    popularity: 78,
    topic: "插画视觉",
    dominantTone: "明亮蓝",
    sourceType: "editorial",
  },
  {
    id: "slide-043",
    title: "Banner 营销页面",
    coverImage: "/images/slides/slide-043.jpg",
    category: "cover",
    scenes: ["品牌营销", "产品发布"],
    tags: ["横幅", "转化感", "促销"],
    style: "营销页面",
    summary: "适合营销活动页、产品推广页和重点转化页面参考。",
    layoutAnalysis: "信息围绕核心卖点展开，视觉路径通常落在标题到 CTA 的链路上。",
    visualFocus: "卖点、产品图和按钮是最关键的三类元素。",
    reusableTips: "如果目的是转化，页面上不要出现多个同等级 CTA。",
    createdAt: "2026-04-12",
    isFeatured: false,
    popularity: 81,
    topic: "营销转化",
    dominantTone: "品牌蓝",
    sourceType: "editorial",
  },
  {
    id: "slide-044",
    title: "日系审美封面页",
    coverImage: "/images/slides/slide-044.png",
    category: "cover",
    scenes: ["品牌营销", "毕业答辩"],
    tags: ["日系", "克制", "留白"],
    style: "轻审美",
    summary: "适合审美向展示、品牌调性页和轻设计风格封面。",
    layoutAnalysis: "通过留白、色彩和小尺度视觉元素建立细腻节奏。",
    visualFocus: "画面气质和局部细节优先于信息密度。",
    reusableTips: "这种页面不适合放太多业务信息，保持呼吸感最重要。",
    createdAt: "2026-04-13",
    isFeatured: false,
    popularity: 73,
    topic: "审美风格",
    dominantTone: "浅粉白",
    sourceType: "editorial",
  },
  {
    id: "slide-045",
    title: "设计灵感展示页",
    coverImage: "/images/slides/slide-045.png",
    category: "case-study",
    scenes: ["商业提案", "教育培训"],
    tags: ["灵感板", "视觉收集", "设计感"],
    style: "灵感陈列",
    summary: "适合设计参考展示、风格合集和视觉灵感整理页。",
    layoutAnalysis: "一页内突出一张强视觉，文本只保留主题与少量说明。",
    visualFocus: "图片本身就是内容核心，页面负责做筛选和陈列。",
    reusableTips: "灵感展示页适合做轻，不要加入过多解释性文本。",
    createdAt: "2026-04-14",
    isFeatured: false,
    popularity: 75,
    topic: "灵感收集",
    dominantTone: "中性白",
    sourceType: "editorial",
  },
];

export const initialCollections: Collection[] = [
  {
    id: "collection-default",
    name: "默认收藏",
    slideIds: ["slide-001", "slide-019", "slide-025"],
    createdAt: "2026-03-01",
    updatedAt: "2026-03-25",
  },
  {
    id: "collection-q2-report",
    name: "Q2述职参考",
    slideIds: ["slide-004", "slide-008", "slide-025"],
    createdAt: "2026-03-05",
    updatedAt: "2026-03-25",
  },
  {
    id: "collection-brand-proposal",
    name: "品牌提案参考",
    slideIds: ["slide-002", "slide-013", "slide-019", "slide-026"],
    createdAt: "2026-03-10",
    updatedAt: "2026-03-26",
  },
];
